/* this file is automatically generated */
#define BUILDDATE "Tue Apr 11 09:29:49 AM EDT 2023"
#define BUILDHOST "shell"
#define BUILDUSER "doc"
#define BUILDOS "Linux 6.2.10-arch1-1"
#define BUILDCC "gcc (GCC) 12.2.1 20230201"
#define VERSION "20230411"
#define BUILDNUM "18581"
