CC = gcc
LD = $(CC)
LIBS = -lm
CFLAGS = -O3
LDFLAGS = -s

#############################################################################

all:         tinyexpr.o

tinyexpr.o:  tinyexpr.h tinyexpr.c

clean:
	rm tinyexpr.o
